#!/usr/bin/env bash

# This is the legacy build of the script I still update this one for machines that don't have aria2.
# Useful for things like raspberry pi's with retropie installed. You can install this script to retropie
# by installing it to /usr/local/bin so you can use it in the shell. You may need to install fzf.
# You can do that by typing "sudo apt install fzf" in the shell. You may also need to update & upgrade the
# packages. You can do that by typing "sudo apt update && sudo apt upgrade".

benis() {
printf "
______  ___              _____            _____ 
___   |/  /____  ___________(_)_____________  /_
__  /|_/ /__  / / /_  ___/_  /_  _ \_  __ \  __/
_  /  / / _  /_/ /_  /   _  / /  __/  / / / /_  
/_/  /_/  _\__, / /_/    /_/  \___//_/ /_/\__/  
          /____/                                
                               Downloader Script
"
}

ibenis() {
benis
printf "
  s) Scraping Term
  d) Download
  t) TUI
"
}

agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.7103.48 Safari/537.36"

please="Please use a option."

url="https://myrient.erista.me/files/"

if [ $# = 0 ]; then
  printf "\n$(ibenis)\n\n"; exit
fi

henis() {
 curl -sA "$agent" "$wombo" \
   | grep "href=" \
   | grep -i "$combo" \
   | awk -v w="$wombo" '{gsub(/<tr><td class="link"><a href="/, w); split($0, a, "\""); print a[1]}' \
   | grep "$wombo" \
   | sed '/<tbody>/d; /\/.\//d; /\/..\//d'
}

check() {
if [ $(printf "${url: -1}") != / ]; then
  wget "$url"
  comdo="$url"
  down_f="$(basename $url | decode_u)"
  fenis; exit
fi
}

check2() {
printf "\n$(benis)\n\nDoing a check. This May Take A Minute...\n\n"
str="$(henis)"
sstr() {
printf %b "$str\n"
}
total_urls="$(sstr | wc -l)"
trailing_urls="$(grep -c '/$' <(sstr))"
clear
if [ $total_urls -gt 0 ] && [ $trailing_urls -eq $total_urls ]; then
  printf "\n$(benis)\n\nDirectories not supported!\n\n"; exit
fi
}

decode_u() {
  perl -pe 's/\%([0-9A-Fa-f]{2})/chr(hex($1))/ge'
}

encode_u() {
  perl -pe 's/([^A-Za-z0-9\-\._~\/\n!])/sprintf("%%%02X", ord($1))/ge'
}

tui() {
  clear
  while true; do
  wombo="$url"
  decode_w="$(printf "%s" "$wombo" | decode_u | sed 's/[][\/.^$*?{}|&]/\\&/g')"
  url_s="$(printf "%b" "Exit\nBack\nLast\nDownload!\n$(henis)" \
    | decode_u \
    | sed "s|^$decode_w|../|g" \
    | fzf --layout=reverse \
    | sed "s|^../||g" \
    | encode_u)"
  if [ "$url_s" = Back ]; then
    url="https://myrient.erista.me/files/"
  elif [ "$url_s" = Last ]; then
    url="$last"
  elif [ "$url_s" = Exit ]; then
    exit
  elif [ "$url_s" = 'Download!' ]; then
    clear
    printf "\n$(benis)\n\nJust hit enter if you want to download all.\n\n"
    read -p "Scraping Term: " -r genis
    clear
    combo="$genis"; aria2_fun; exit
  elif [ -z "$url_s" ]; then
    :
  else
    url="$wombo$url_s"
    check
  fi
    last="$wombo"
done
}

dhenis() {
  printf "\n$(benis)\n\nThis May Take A Minute...\n" 1>&2 && curl -vsA "$agent" $(henis) 2>&1 \
    | grep -i '< Location:' \
    | awk '{print $3}' \
    | tr -d '\r'
}

wget_fun() {
  url="$wombo"
  check
  clear
  check2
  printf "\n$(benis)\n\nDownloading...\n"
  down_u="$(grep -v '/$' <(sstr))"
  down_f="$(basename -a $down_u | decode_u)"
  for i in $down_u; do
    wget "$i"
  done
  grep '.zip' <(sstr) >/dev/null
  if [ $? = 0 ]; then
    comdo='.zip'
  fi
fenis
}

fenis() {
  zip_e() {
    printf "%s" "$down_f" | grep -i '\.zip$'
  }
  if printf "%s" "$comdo" | grep '.zip' >/dev/null; then
  clear
  printf "Do you want to extract and remove zip(s)? \
(y/n) *This will 'EXTRACT' and or 'DELETE' other zip files that may be in the directory*\n\n"
  read -r gombo
  case "$gombo" in
    y|Y) zip_e | xargs -d '\n' -I {} unzip "{}" && zip_e | xargs -d '\n' -I {} rm "{}";;
    n|N) printf "Ok then.\n";;
      *) printf "Umm.. ok I'll just pick no...\n";;
  esac
  clear
  printf "Done! :-p\n"
fi
}

while getopts "s:d:th" denis; do
case "$denis" in
  s) combo="$OPTARG" 
  ;;
  d) wombo="$OPTARG"; wget_fun; exit
  ;;
  t) tui; exit
  ;;
  h) printf "\n$(ibenis)\n\n"
  ;;
  *) printf "\nSorry I didn't get that.\n\n$please\n\n"
  ;;
esac  
done
